name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
      env:
        NODE_ENV: development
        PORT: 5001     
        API_KEY: ${{ secrets.API_KEY }}
    - run: npm test -- --passWithNoTests
    - name: Ensure app is running with PM2
      run: |
        # Check if the app is running and start it if not
        pm2 show api-cups || pm2 start ecosystem.config.json
        pm2 restart api-cups
